### ISSUE TITLE
Unable to install - error = Integration error: button_card_templates - Integration 'button_card_templates' not found

### ISSUE THREAD

**Issue by Tomadoggy** [wfurphy/creative-button-card-templates#10]
I have done my best to follow the installation instructions but get the error: Integration error: button_card_templates - Integration 'button_card_templates' not found

I have the cloned git here in the root of config:

![Image](https://github.com/user-attachments/assets/60d5d6d1-5f18-4d7a-ba45-39d5bc7f7724)

And also tried to install here:

![Image](https://github.com/user-attachments/assets/7b0c7b5f-5d6d-403f-bff3-1c1df8b6f13a)

and this addition to my configuraiton.yaml

![Image](https://github.com/user-attachments/assets/d88a9cbb-4498-4f1d-a440-cba2f638fb28)

Also created a file titled ui-lovelace.yaml

![Image](https://github.com/user-attachments/assets/41c5f83b-1c6d-42c8-b4ef-1c05d3d47912)

Any assistance greatly appreciated!

**Comment by wfurphy** [comment]
Hi Tomadoggy,

Sorry for the delay in getting back to you on this one. You've got everything right except for `configuration.yaml` You should remove the code snippet that you added there. 

If you want to use dashboards in YAML mode (editing them in the files) then you should add the following to your `configuration.yaml`:

```yaml
lovelace:
  mode: yaml
  resources: !include ui-resources.yaml
```

Then the code snippet you have added in the `ui-lovelace.yaml` is good but you'll also need to define the dashboards in there...

```yaml
#######################################################################################################################>
#### Button Card Templates for Home Assistant Lovelace dashboards
#### Will Furphy | https://github.com/wfurphy/ha-button-card-templates
#### Requires https://github.com/custom-cards/button-card
button_card_templates: !include_dir_merge_named dashboards/templates/
###################################################################################################/

title: Dashboard
show_in_sidebar: true
icon: mdi:view-dashboard
views:
  # Specify your views here...
```
