### ISSUE TITLE
[Question] Plug information

### ISSUE THREAD

**Issue by SirHamburger** [wfurphy/creative-button-card-templates#9]
Hello, 

I'm trying to add a plug with the current and voltage. 
I have a meross switch with the following entities/attributes:

![Image](https://github.com/user-attachments/assets/5d199a18-d3b1-474f-9c2c-ff9400664986)

I added a new plug template as the following:

![Image](https://github.com/user-attachments/assets/e48dff5d-974d-4338-9a72-dbeda2b9a156)

But since the attributes current and voltage are on a different entity, they are not shown. Is it possible to use your template with my setup, and if yes how? 

(I'm kind of a noob in Home Assistant, so sorry if it's obvious)

**Comment by wfurphy** [comment]
Hi SirHamburger,

Sorry about the exceptionally belated reply on this one! If it's still useful, I have a solution for you.

The current release doesn't support displaying entities as attributes through the `device` template. However, I've been working on the next version and using them for my own cards and what you're looking for is actually available on the `develop` branch. I don't know if you want to clone all of the code from that branch, as there are a few breaking changes, and the documentation is not up to date. However, Here are some instructions if you want to do a quick patch. 

1. Add [entity.yaml](https://github.com/wfurphy/creative-button-card-templates/blob/b266ce6d0572e2818266796b97f89b4e23b9c0a7/entity.yaml) to your `creative-button-card-templates` directory. 
2. Replace your existing `device.yaml` with [device.yaml](https://github.com/wfurphy/creative-button-card-templates/blob/b266ce6d0572e2818266796b97f89b4e23b9c0a7/device.yaml) 
3. Make yourself a new card, specifying `id: state` and `entity: {{ entity_id }}` for each attribute then it'll load the state of those entities as the attributes. If you don't specify `units`, it will use the ones from the entity, but you'll need to set your own `icon`. Here's an example:

```yaml
type: custom:button-card
template: entity
entity: binary_sensor.myroom_window_contact
name: MyRoom Window
variables:
  attributes:
    - id: state
      entity: sensor.myroom_window_battery
      icon: mdi:battery
    - id: state
      entity: sensor.myroom_window_device_temperature
      icon: mdi:thermometer
```

The `plug` template just uses `device`/`entity` but has the attributes predefined, so you'll get the same result by using `entity` and specifying the attributes manually like in the example above.
